### ISSUE TITLE
Documentation | Guide - Add Icons

### ISSUE THREAD

**Issue by AntoineKM** [tonightpass/kitchn#68]
Reference:
https://geist-ui.dev/en-us/components/icons

**Comment by maddy020** [comment]
Please give details over the issue

**Comment by AntoineKM** [comment]
Hello @maddy020 !

Regarding the Icons, as you may have noticed we use a third party library for those called `react-icons`, I've indicated what we are referring to just above!

As for #70 you just need to create a documentation in ``./docs/pages/docs/guides/icons.mdx`` from ``./examples/next-typescript/pages/button.tsx`` without forgetting to mention ``react-icons`` or even to specify that it is possible to use another library or just an svg as long as it is an svg
